FROM python:3.11-slim

WORKDIR /app

COPY Analystics_Service/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY Analystics_Service .
COPY Data ./Data
CMD ["python","Consumer.py"]